### ISSUE TITLE
Wrapper functions for various type of templates

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#106]
Might be worth it to write a series of functions like `add_miniminal()` that would do `add_dev_history(type = "minimal")`, `add_full` that would do `add_dev_history(type = "minimal")`, etc.

**Comment by statnmap** [comment]
New version of {fusen} goes with `add_flat_template("min")` as I changed the order of parameters and partial matching works.  
But we can think of shorter path!
