### ISSUE TITLE
`add_flat_template` using wrong folder for `inflate` when `dev_dir` is not `dev`

### ISSUE THREAD

**Issue by mone27** [ThinkR-open/fusen#115]
I'd like to have my files under `code` instead of `dev` and this is supported by `fusen`.

If I run the code:
`fusen::add_flat_template(template = "minimal", dev_dir = "code", flat_name = "name")`
it correctly creates a file under `code` called `flat_name.Rmd`

In the last chunk of the template there is the code to inflate the template, which is however incorrect.
What I get is:
`fusen::inflate(flat_file = "dev/flat_name.Rmd", vignette_name = "Minimal")`

while what I'd expect is:
`fusen::inflate(flat_file = "code/flat_name.Rmd", vignette_name = "Minimal")`

It seems that `dev_dir` is not taken  into account when generating the template.

**Comment by statnmap** [comment]
Thanks. I fixed it (https://github.com/ThinkR-open/fusen/pull/117)
Please tell me if this does not work as expected.
