### ISSUE TITLE
filename chunk param should strip trailing .R if added

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#116]
```
	```{r function-fct_build_basket_content, filename = "fct_build_basket_content.R"}
```

Will create a file called `fct_build_basket_content-r.R`, which is probably not what we are looking for?

**Comment by statnmap** [comment]
Thanks. I fixed it (https://github.com/ThinkR-open/fusen/pull/117)
Please tell me if this does not work as expected.
