### ISSUE TITLE
Do not ignore golem dev files 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#122]
If I create a golem app, I'll have added to my dev script a gitignore with: 

```
*.html
*.R
```

Issue is that I want to commit 01_start.R, 02_dev.R and 03_deploy.R 

What's the rational behind this gitignore? Can we not have it when in golem?

**Comment by ALanguillaume** [comment]
Yes this was a regrettable copy pasting from that usethis does in `vignettes/`.
This was solved in https://github.com/ThinkR-open/fusen/pull/94
Re-installing fusen should solve this.
