### ISSUE TITLE
Make fusen::inflate() self-aware

### ISSUE THREAD

**Issue by dmi3kno** [ThinkR-open/fusen#14]
You can track where the `fusen::inflate()` is called from and use it as an rmd/path argument, if nothing else is provided.

## Tech

- Read parameters from YAML of the current flat file: https://github.com/ThinkR-open/fusen/issues/191

**Comment by statnmap** [comment]
This issue is listed in the future roadmap. It will be re-opened when necessary. See: https://github.com/ThinkR-open/fusen/wiki/Future-road-map
