### ISSUE TITLE
Line break before function() provoke unexpected problem

### ISSUE THREAD

**Issue by pwaeckerle** [ThinkR-open/fusen#142]
# Criteria of validation

All the below cases are tested with a specific flat test file: https://github.com/ThinkR-open/fusen/blob/main/inst/tests-templates/dev-template-function-name-linebreak.Rmd

The use of the following codes in a flat file do not affect the correct detection of the function real name :

- [ ] linebreak, roxygen before
```
#' fake_name
real_name <- 
   function()
```

- [ ] linebreak, comment before
```
#' fake_name
# a comment
real_name <- 
function()
```

- [ ] comment between name and linebreak
```
#' fake_name
real_name <- # a comment
function()
```

- [ ] commented line between name and linebreak
```
#' fake_name
real_name <- 
# a comment
function()
```

- [ ] linebreak, nothing before
```
real_name <- 
   function()
```

- [ ] no linebreak, comment before
```
#' fake_name
# a comment
real_name <- function()
```

- [ ] no linebreak, code before
```
sqrt(1)
real_name <- function()
```

- [ ] no linebreak, nothing before
```
real_name <- function()
```

- [ ] linebreak, roxygen before, symbol "="
```
#' fake_name
real_name  =
   function()
```

# Technical

Proposition 1 : detect the 1st assignment arrow in the code that is not in a comment or a roxygen
Propostion 2 : combine the line above in paste(line_before, line). A line break turns into a space, and there is no risk of catching a different name

- Create a new test Rmd file there to create the problem (the different code snippets to be validated) : https://github.com/ThinkR-open/fusen/tree/main/inst/tests-templates
- Add a new unit test in https://github.com/ThinkR-open/fusen/blob/main/tests/testthat/test-inflate-part2.R
- Debug the source of the function
    - the problem is in `parse_fun()`, which uses this regex for each single line: https://github.com/ThinkR-open/fusen/blob/bc84590356803353b5eb101cbb276c6fd1003d8a/R/inflate-utils.R#L18
----
# Problem description

When adding a line break between the affectation sign and the `function` keyword, fusen does not handle correctly the flat file content.

> This line break can be added by the user, but more surely by the RStudio reformat shortcut.

fusen shows warning messages that alerts the user :

```r
Updating mypkg documentation
ℹ Loading mypkg
Warning: [/home/rstudio/mypkg/R/my-function.R:8] @examples requires a value
Writing NAMESPACE
Writing NAMESPACE
Writing debug_fusen.Rd
```

In the output, the vignette is created as expected but the .R file has the name of the makdown title above the function description in the flat file.

# Reprex
## Working example

I use a minimal flat file with the following function description and example (no test) :
```r
# My function

```{r function-debug_fusen}
#' debug_fusen
#'
#' @return 1
#' @export
#'
#' @examples
debug_fusen <- function() {
  1
}
```

```{r examples-debug_fusen}
debug_fusen()
```

When inflating, we have : a debug_fusen.R file in R\ and a vignette corresponding to the _vignette_name_ attribute in the fusen::inflate() call.

### Not working example

The same cas as below, with the simple addition of a line break before _function_ :

```r
# My function

```{r function-debug_fusen}
#' debug_fusen
#'
#' @return 1
#' @export
#'
#' @examples
debug_fusen <- 
  function() {
  1
}
```

```{r examples-debug_fusen}
debug_fusen()
```

When doing the inflate, we have :

* Warning message (see above) regarding the absence of a function example,
* The vignette updated (still well located thanks to the filename argument),
* a _my_function.R_ file created with no example in it.

**Comment by FlorenceMounier** [comment]
Problem: in `R/inflate-utils.R`,  `parsermd::rmd_node_code()` splits code by reading line breaks (1 value = 1 line).
Proposition : add a new regex that would detect the pattern "<-" in "my_fun <- " and bind this value with the value returned by the regex `regex_isfunction` that detects the value "  function() {"

**Comment by statnmap** [comment]
That should be good now.  
Merged in: https://github.com/ThinkR-open/fusen/pull/186  
Please tell us if your face again the problem
