### ISSUE TITLE
bug: Flat template with multi chunk examples

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/fusen#149]
In a flat template, if a function has more than 1 `examples` chunk, the function code is duplicated in the .R file and .Rd (man).

` ```{r examples-myfun_1} ``` `

` ```{r examples-myfun_2}``` `

**Comment by statnmap** [comment]
That should be good now.  
Fixed in this commit: https://github.com/ThinkR-open/fusen/commit/f1f52d3d97b9f8e83cbcb2e419f5d057fc7624db
