### ISSUE TITLE
Remove spaces in the function name with the RStudio Addin 'Add fusen chunks'

### ISSUE THREAD

**Issue by MargotBr** [ThinkR-open/fusen#164]
## Validation

- [x] Mistake in function name is cleaned before building chunks
![image](https://github.com/ThinkR-open/fusen/assets/21193866/383aced5-df1c-4e36-ab9e-fc28909690cc)

## Tech
When there is a mistake in the function name (a space):

![Capture d’écran 2022-09-05 à 10 26 51](https://user-images.githubusercontent.com/20540890/188404007-395f3ed4-b42a-444b-9891-ffd9fe0077ee.png)

The space is not removed in the chunks:

![Capture d’écran 2022-09-05 à 10 27 16](https://user-images.githubusercontent.com/20540890/188404074-b6ddf866-cdfd-48a4-b4e5-321a63a706ec.png)

See to use `str_trim()` when the chunks are created

**Comment by statnmap** [comment]
We will avoid using {stringr}, but we can probably tweek `asciify_name()`. It may also benefit to vignettes names.

**Comment by statnmap** [comment]
This probably goes with: https://github.com/ThinkR-open/fusen/issues/172
