### ISSUE TITLE
add {fusen} chunk addin doesn't work when Rmd is in "new window" (floating Rstudio windows)

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/fusen#168]
how to reproduce : 

first detach the Rmd using this button
![image](https://user-images.githubusercontent.com/10470699/192138130-5261386a-66dc-48e6-bb9e-c2a6c5a050f1.png)

![image](https://user-images.githubusercontent.com/10470699/192138101-6f817c7b-4f9b-4986-b1ee-6a8130e8c4ae.png)
![image](https://user-images.githubusercontent.com/10470699/192138112-f2234c60-c202-4293-a21e-6567a123ac57.png)

**Comment by statnmap** [comment]
This issue is listed in the future roadmap. It will be re-opened when necessary. See: https://github.com/ThinkR-open/fusen/wiki/Future-road-map
