### ISSUE TITLE
`inflate()` should allow passing extra parameters to `attachment::att_amend_desc()`call

### ISSUE THREAD

**Issue by ymansiaux** [ThinkR-open/fusen#184]
`fusen::inflate()` creates the package documentation using `attachment::att_amend_desc()`.

It could be useful to allow passing extra_parameters to `attachment::att_amend_desc()` call, 

e.g. `attachment::att_amend_desc(
  extra.suggests = c("dplyr")
)`

**Comment by statnmap** [comment]
Unfortunately, that won't be possible.  
Indeed, the `...` can only be used for one of the internal function. Here, there are already used for `devtools::check()`.   
I will however think of the package differently by using a configuration file.  Transition is on going with this milestone: https://github.com/ThinkR-open/fusen/milestone/2  
Maybe {attachment} could also have its own configuration file that could be read by {fusen}.

**Comment by ymansiaux** [comment]
Regarding this issue, adding the following to the `inflate()` function in the file R/inflate.R, could be an option to be considered for a future version of `{fusen}` :

We could add an argument `att_amend_desc_params` to the `inflate()` call, which will be a named list of `attachment::att_amend_desc()` arguments, e.g :

`att_amend_desc_params <- list(extra.suggests = c("dplyr", "tidyr"), pkg_ignore = "ggplot2", normalize = TRUE)`

It would be needed to add the following to the function : 

```
if(isTRUE(document)) {
  if(class(att_amend_desc_params) != "list") {
    stop("att_amend_desc_params must be a list")
  }
  
  if(length(att_amend_desc_params) > 0) {
    if(!all(names(att_amend_desc_params) %in% formalArgs(attachment::att_amend_desc))) {
      stop("Some names of the list att_amend_desc_params do not correspond to attachment::att_amend_desc() arguments")
    }
  }
  
  # Run attachment  
  att_amend_desc_params <- att_amend_desc_params[!names(att_amend_desc_params) %in% "pkg"]
  
  do.call(attachment::att_amend_desc,
          c(
            list(path = pkg),
            att_amend_desc_params
          )
  )
}
```

**Comment by statnmap** [comment]
I think I will go for this: https://github.com/ThinkR-open/attachment/issues/75  
This will make things easier for non-fusen packages too.

**Comment by statnmap** [comment]
Your proposition was a good idea though.

**Comment by statnmap** [comment]
{attachment} v0.4.0 now stores parameters used once, so that `fusen::inflate()` can use it directly without having to change the current source code.
Run your `attachment::att_amend_desc(extra.suggests = c("dplyr", "tidyr"), pkg_ignore = "ggplot2", normalize = TRUE, update_config = TRUE)` in the "dev/0-dev_history.Rmd" file and run it only if you change it. If it did not change since last time, `fusen::inflate()` will use the last version. 
See: https://thinkr-open.github.io/attachment/
