### ISSUE TITLE
feat: As a GolemDev, I would like 0-dev_history to not be added

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#187]
## Validation

- [x] Documentation explicitly state that using the "additional" template does not override or add a 0-dev_history.Rmd.  
![image](https://github.com/ThinkR-open/fusen/assets/21193866/bbee38c0-ac6a-456d-a663-8e42ac41d232)

- [x] There is a section on how to use {fusen} with {golem} in the Tips and tricks vignette.  
![image](https://github.com/ThinkR-open/fusen/assets/21193866/d2279a36-4546-448b-90c1-ebeb4035d748)

## Context

i'm not sure the dev_history file should be enforced on project that weren't initialized with {fusen}, or at least there should be an option to ignore it.

When dev with {golem}, forcing this file is redundant with what you've got in other files.

Reprex : 

```
colinfay@Colins-MBP ~ % cd /tmp 
colinfay@Colins-MBP /tmp % Rscript -e "golem::create_golem('pif')"
[REDACTED]
A new golem named pif was created at pif .
To continue working on your app, start editing the 01_start.R file.
colinfay@Colins-MBP /tmp % cd pif 
colinfay@Colins-MBP pif % Rscript -e "fusen::add_minimal(flat_name = 'graph')"
File .here already exists in /private/tmp/pif
[1] "/private/tmp/pif/dev/flat_graph.Rmd"   
[2] "/private/tmp/pif/dev/0-dev_history.Rmd"
```

## Validation 

- If I run fusen::add_mininal() in a golem project, I don't have 0-dev_history

**Comment by ALanguillaume** [comment]
@ColinFay you need to use `fusen::add_additional()` for that purpose. It will only add a new flat file and no 0-dev_history.Rmd

Re-reading the documentation, I realised that it is not explicitly mentionned anywere. 

May be we can:

* explicitly state that using the "additional" template does not override or add a 0-dev_history.Rmd.
* Add a section on how to use {fusen} with {golem} in the Tips and tricks vignette.

**Comment by statnmap** [comment]
This issue is listed in the future roadmap. It will be re-opened when necessary. See: https://github.com/ThinkR-open/fusen/wiki/Future-road-map
