### ISSUE TITLE
As dev, I want that the yaml header of a flat file contains the arguments of the `inflate()` call

### ISSUE THREAD

**Issue by ymansiaux** [ThinkR-open/fusen#191]
This feature will be required to be able to inflate() the current flat file with its own parameters: https://github.com/ThinkR-open/fusen/issues/14

# Validation

- [ ]  The first time that the user runs the `{r development-inflate}` chunk, the header of the flat Rmd file is updated with the values of the arguments of the `inflate()` call. If some arguments are missing, the default values are used.
- [ ] Each subsequent run of this chunk updates the yaml header accordingly
- [ ] If a user uses the `inflate()` function with no argument in the R terminal, the current flat Rmd file is inflated
  - [ ] If the yaml header contains no arguments to be used in `inflate()` the user is warned that the default parameters are going to be used
  - [ ] Otherwise, the arguments listed in the yaml header are used and there is a message in the R terminal which list the arguments used
- [ ]  The inflate parameters of each flat file is stored in the "config_fusen.yml" file, during the first full inflate of this flat file.
- [ ] The file "config_fusen.yml" is updated each time the inflate parameters of a flat file are modified

# Tech

- Retrieve the full content of the "inflate" chunk to get the parameters. That may be easier inside the `inflate()` function itself because all params are there: See https://github.com/ThinkR-open/fusen/issues/190
- Think about a way to store the inflate options inside the "fusen_config.yaml" file, as with files list
    - Use a specific function `flat_params_to_config()`, even used to define the `state` already implemented 
- Note  that I can run the `inflate()` without parameters

To be defined ...

In future version of {fusen} should the yaml header be pre-filled with the default arguments ?

**Comment by ymansiaux** [comment]
Notes for me :

- find how to be able to parse the content of the inflate() call
- find how to be able to write in the yml header of the rmd flat file
- find how to be able to parse the yml header of the rmd flat file in order to put these information in the main config file

**Comment by ymansiaux** [comment]
See pkg {parsermd}
https://rundel.github.io/parsermd/

**Comment by statnmap** [comment]
This issue is listed in the future roadmap. It will be re-opened when necessary. See: https://github.com/ThinkR-open/fusen/wiki/Future-road-map
