### ISSUE TITLE
As dev I want `df_to_config()` to be able to add a list of `inflate()` parameters in the `config_fusen.yml` file

### ISSUE THREAD

**Issue by ymansiaux** [ThinkR-open/fusen#194]
## Objective

* Modify `config_fusen.yml` to be able to store `fusen::inflate()` parameters

`config_fusen.yml` currently stores some informations, for instance a list of the .R files, unit tests files and vignettes associated to each flat file. This is done through `fusen::df_to_config()`.
This function must be modified to be able to store `fusen::inflate()` parameters in `config_fusen.yml`

## Validation

- [x] `df_to_config()` has a parameter `inflate_parameters` which corresponds to a list of parameters used in a `fusen::inflate()` call

https://github.com/ThinkR-open/fusen/blob/194-add_inflate_param_to_config_fusen/R/clean_fusen_files.R#L223

~~- [x] `fusen::inflate()` can pass a list of `inflate_parameters` to df_to_config :~~

~~https://github.com/ThinkR-open/fusen/blob/194-add_inflate_param_to_config_fusen/R/inflate.R#L273~~

-> moved to https://github.com/ThinkR-open/fusen/issues/196

- [x] `df_to_config()` can pass the list of inflate_parameters to `update_one_group_yaml()`, the function which will append the inflate() call parameters to the `config_fusen.yml` file.

https://github.com/ThinkR-open/fusen/blob/194-add_inflate_param_to_config_fusen/R/clean_fusen_files.R#L387

- [ ] `update_one_group_yaml()` is able to append the inflate parameters to the  `config_fusen.yml` file.

https://github.com/ThinkR-open/fusen/blob/194-add_inflate_param_to_config_fusen/R/clean_fusen_files.R#L511

- [ ] an example is shown

https://github.com/ThinkR-open/fusen/blob/194-add_inflate_param_to_config_fusen/man/df_to_config.Rd#L61

- [ ] the new functionnality is tested

https://github.com/ThinkR-open/fusen/blob/194-add_inflate_param_to_config_fusen/tests/testthat/test-clean_fusen_files.R#L330

lines 330 -> 436

- [ ] all test are passing

![image](https://user-images.githubusercontent.com/49268931/228277338-a7f85b88-30ac-410e-99f8-08801871a95b.png)

## Dev

- [x] add a new parameter called `inflate_parameters` to the function `df_to_config`
- [x] inflate_parameters must be a list: e.g `list(pkg = ".", vignette = "toto", ....)`
- [ ] find a way to put these parameters below the other parameters describing the flat_file,
  - [x]  it can probably be done during the call of the function `update_one_group_yaml()`
  - [ ]  or just after the call of this function, when it could be appended to the object `all_groups_list` 
- [x] modify the units tests

**Comment by ymansiaux** [comment]
Hi @statnmap , could you please take a look at this issue please

See the associated PR : https://github.com/ThinkR-open/fusen/pull/195

**Comment by statnmap** [comment]
Please see my comments directly in the PR: https://github.com/ThinkR-open/fusen/pull/195#pullrequestreview-1361492018

**Comment by ymansiaux** [comment]
Issue was merged
