### ISSUE TITLE
Adding the test "expect_true(inherits()" when using add flat template addins 

### ISSUE THREAD

**Issue by ronysym** [ThinkR-open/fusen#243]
During a ThinkR N2 training, in the Bakacode.io environment;  When using the Fusen addin: add_flat_template "additonnial", the chunck "test" does not integrate by the test: expect_true(inherits(function_name, "function"))

![image](https://github.com/ThinkR-open/fusen/assets/54936128/9e539b52-8ea2-48e5-98c2-193cc997ffd9)

While when using addins add_chunk this test is included automatically

![image](https://github.com/ThinkR-open/fusen/assets/54936128/e06b51fe-410b-4f3b-a045-0469f14a51cc)

**Comment by statnmap** [comment]
Thanks for raising the issue.  
This is now fixed in the dev version of 'fusen' through this PR : https://github.com/ThinkR-open/fusen/pull/247
