### ISSUE TITLE
ERROR: dependency 'parsermd' is not available for package 'fusen' OR C++14 standard requested but CXX14 is not defined

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#30]
For Windows users, R should be bigger than R 4.0 to be able to install dependency {parsermd} (See https://github.com/rundel/parsermd/issues/26).  

Maybe a lower feature version of {fusen} can be used for these specific users from "dev/dev_history_parse.Rmd"

**Comment by philippecourteix** [comment]
Hi, same issue on Centos7 and R 4.0.2. Unable to install fusen package with error : ERROR: dependency ‘parsermd’ is not available for package ‘fusen’

**Comment by statnmap** [comment]
Hi,
Are you able to install {parsermd} directly using `install.packages("parsermd")` ?
It may need some extra system dependencies.

**Comment by philippecourteix** [comment]
Hi, thanks for your reply.
I have check system parsermd dependancies, and effectively c++14 is not installed.  So, i will contact our system team to install it.
Regards.

**Comment by statnmap** [comment]
We plan to remove {parsermd} from dependencies, but this is a big change.

In the meantime, you can install {parsermd} from this patched version on my personal r-universe.
This avoids forcing C++14 installation.  
I hope this helps: 
```r
install.packages('parsermd', repos = c('https://statnmap.r-universe.dev', 'https://cloud.r-project.org'))
```

**Comment by statnmap** [comment]
This should be ok in the current GitHub version of 'fusen'.  
This will be included in the next release
