### ISSUE TITLE
How to load internal package from Jenkins 

### ISSUE THREAD

**Issue by uriahf** [ThinkR-open/fusen#32]
Hi, this question is more related to the Rmd First method rather than specifically the {fusen} package, but it seems relevant and I didn't know where to ask it.

I run a project as a package and I've got a Jenkinsfile that runs the r scripts. I can include all the content from the "R" file manually and than run a specific script that calls to the specific functions that I want to run. 

It might lead to the desired result but I guess that it's a bad practice. 

I hope that the description was clear enough.

**Comment by statnmap** [comment]
I am not sure I see the link between Jenkins, the Rmd-First and the package.  
If you are in a package, then your CI can install it. This means that functions are available and there is no need to load the R/ directory. You call `library(mypackage)` instead.  

What am I missing ?

**Comment by uriahf** [comment]
It wasn't obvious to me that you need to reinstall the package every time as part of the automation process. 

I'm afraid that building a package might be more complex to run in a container than just call `source()` on the relevant functions. Maybe calling devtools::build(vignettes = FALSE) might help avoiding unecessary burden? I am trying to avoid unecessary dependencies for package building.

**Comment by statnmap** [comment]
You only need {remotes} to install the package: `remotes::install_local()`.  
This allows you to install dependencies necessary for your functions to work correctly. 

If you `source()` there is no way to know if you have the dependencies required correctly installed. 
There is also no warning to you as a developer to know that you listed all dependencies.
By using a package and checking it before sharing, you assure your users that all dependencies are listed in DESCRIPTION.
You can have some help with {attachment} for that.
And using {remotes} to install your package will also install required dependencies.

**Comment by uriahf** [comment]
Thank you, this was really helpful and I managed to install the package as part of the automation process!

It will be extremely useful to have a specific place for questions about the Rmd First method, there is a steep learning curve for package development and specially as a workflow for regular projects. I can't think of a good place where I can ask related questions or give some good answers that I might have thought about previously, it's extremly important for me because my collegues tackle me with related difficulties.
