### ISSUE TITLE
Help deal with dataset

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#4]
To go further than what is presented in the tips & tricks: https://thinkr-open.github.io/fusen/articles/tips-and-tricks.html#document-your-internal-datasets-in-a-function-chunk-as-usual

Use a chunk named `data` where you can read data as in a classical Rmd.  
Detect path to dataset, copy it to `inst` and transform path as `system.file()` for examples and tests.  
Detect named given to dataset object if use in examples and tests, to add data read in these parts too.

**Comment by statnmap** [comment]
Make {fusen} work with documented datasets

```{r function}
#' mon jeu de données
#'
#' Un jeu de données contenant un bout d'iris
#'
#' @name mes_data_nettoyees
#' @docType data
#' @author Colin \email{colin@@thinkr.fr}
#' @source \url{google.com}{unlien}
#' @format data.frame
#' @keywords data
"mes_data_nettoyees"
```

**Comment by tbesse-oeb** [comment]
I was just looking for this feature !

If I understand the ["Tips and triks"](https://github.com/ThinkR-open/fusen/issues/84) page correctly, if I want to include a dataset in my package : 
- I use a "development" chunk to write the script used to create the dataset (ending with `usethis::use_data(substances_actives, overwrite = TRUE)` to store it in data/) 
- I use a "function" chunk to document the dataset

Will fusen create the .R file in data-raw with the creation script when inflating the package ?

**Comment by statnmap** [comment]
This issue is listed in the future roadmap. It will be re-opened when necessary. See: https://github.com/ThinkR-open/fusen/wiki/Future-road-map
