### ISSUE TITLE
`fusen::add_dev_history(name = )` might be misleading

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#48]
When using `fusen::add_dev_history(name = )`, I would expect the name to be the name of the Rmd, not the name of the template. 

I think a more appropriate param name would be `template` :)

**Comment by ColinFay** [comment]
One approach could be : 

```r
add_dev_history <- function(template = c("full", "minimal", "additional", "teaching"), 
                            name = NULL) {
  if( !is.null(name) ){
    warning("The `name` argument to `add_dev_history()` is deprecated since {fusen} version xyz, and will be removed in a future version.\nPlease use `template` instead.\n")
    template <- name
  }     
}
```

**Comment by statnmap** [comment]
Indeed, if we do not use `name` anymore, that's good. Then to choose myself a filename, I can call it `filename`
