### ISSUE TITLE
Allow the user to set the Rmd field in add_dev_history

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#53]
`fusen::add_dev_history(title = "", author = "", extra_params = c(x = ""))`

**Comment by statnmap** [comment]
The title now contains the `flat_name` parameter: https://github.com/ThinkR-open/fusen/commit/2bb5b197301262b34b0bb35c4e940baccbd017eb
The author is not really meaningful here.  
Hence:
`fusen::add_flat_template(flat_name = "my-family")`
will lead to 
```
title: "flat_my-family.Rmd"
```
