### ISSUE TITLE
Automatically add the roxygen skeleton in the template

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#54]
Something like

```
	  # My function
	  
	  ```{r function}
	  #' title 
	  #'  
	  #' Description 
	  #' 
	  #' @export 
	  ```

```

**Comment by statnmap** [comment]
flat_templates additional and minimal, as well as the addin have a minimal roxygen skeleton.
![image](https://user-images.githubusercontent.com/21193866/144498780-d7be19d8-f664-44af-be9e-cbcecddcbe4c.png)
