### ISSUE TITLE
Extending {fusen} with your own template. 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/fusen#61]
We may want to allow user to define their own template. 

I can imagine something like: 

```r
fusen::add_dev_history(template = golem::module_dev) 
```

**Comment by ColinFay** [comment]
I think we could have something like: 

```
if ( inherit(template, "function") ){
	template_file <- template()
}
```

Where we can provide a function that returns a file_path with a template

**Comment by FlorenceMounier** [comment]
@ColinFay maybe this new feature should also handle the file path directly?

**Comment by statnmap** [comment]
This issue is listed in the future roadmap. It will be re-opened when necessary. See: https://github.com/ThinkR-open/fusen/wiki/Future-road-map
