### ISSUE TITLE
Vignette: Tips and tricks

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#84]
## How to include examples that cannot be run ?
I created a chunk `example` but I do not want the example to be run in the function example and I do not want it to be run in the vignette.
- Use `eval=FALSE` in the chunk options, so that it wont be run in the vignette
- Use `#' \dontrun{}` syntax, with `#' ` before so that examples in the function example will not be run

  
      ```{r function-myfunction}
      myfunction <- function(x) {x}
      ```
      
      ```{r example-myfunction, eval=FALSE}
      # Will be run in example but not in vignette
      myfunction(10)
  
      # Will not be run in example
      #' \dontrun{
      myfunction(12)
      #' }
      
      #' \dontrun{
      #' myfunction(12)
      #' }
      ```

## Document your internal datasets in a `function` chunk as usual
- Explain how to document datasets, pkgdoc, special R files: Linked to https://github.com/ThinkR-open/fusen/issues/4
- If there is no proper function, the chunk is copied as is in a R file.
```
#' cars
#'
#' data in 'datasets'.
#'
#' @format A data frame with 50 rows and 2 variables:
#' \describe{
#'   \item{ speed }{  numeric }
#'   \item{ dist }{  numeric }
#' }
#' @source Ezekiel, M. (1930) Methods of Correlation Analysis. Wiley.
"cars"
```

## How to ignore some chunks ?

All chunks named `dev` or `development` will not be used in the package.  
Use them for your exploration that you do not want to keep at the end of the process. 
This won't affect your package.

## How not to create a vignette ?

- If I only build internal functions, I may not want to inflate the flat file as a vignette. 
- The flat_file is the developer's documentation and that is enough
```r
inflate(vignette_name = NA)
```

## How to get a pre-filled template for a specific function name ?

- If it is the first function of the template, then you can create the template with `add_flat_template("minimal", flat_name = "my_function_name")`.  In this case, the template will be pre-filled with your function name: chunk names, function calls.
- If this is the second function inside an existing template, position your prompt where you want to add the new function and use the RStudio Addin: "Add {fusen} chunk" 
- The addin uses `add_fusen_chunks("my_function_name")`

## How to Inflate multiple flat files ?

- Add an entry in your main dev_history.Rmd
```r
fusen::inflate("dev/flat_file1.Rmd")
fusen::inflate("dev/flat_file2.Rmd")
fusen::inflate("dev/flat_file3.Rmd")
```

If the main "dev_history.Rmd" does not exists, create it with `add_flat_template("dev_history")`

## How to store multiple functions in a unique R file ?

There are multiple ways of doing it. Choose one of: use the section title structure, use roxygen tags or use chunk parameter.

### All in one section
 Use the 3-set of chunks (fun, example, test) twice, under the same title section of the Rmd
- https://github.com/ThinkR-open/fusen/issues/57

```md
# One title for both groups of chunk

 The code and tests for the first function

-- chunk fun --
-- chunf example --
-- chunk test --

 The code and tests for the second function

-- chunk fun --
-- chunf example --
-- chunk test --

```
### Use same `@rdname` in function roxygen

```md
# Title 1 for function 1

``{r function-fun_rdname1}
#' My fun_rdname1
#'
#' @param x Vector of Numeric values
#' @inheritParams stats::median
#'
#' @rdname same_rdname
#' @return
#' Median of vector x
#' @export
#'
#' @examples
#' my_fun_rdname1(2:20)
my_fun_rdname1 <- function(x, na.rm = TRUE) {
  if (!is.numeric(x)) {stop("x should be numeric")}
  stats::median(x, na.rm = na.rm)
}
``

# Title  2 for function 2

``{r function-fun_rdname2}
#' My fun_rdname2
#'
#' @param x Vector of Numeric values
#' @inheritParams stats::median
#'
#' @rdname same_rdname
#' @return
#' Median of vector x
#' @export
#'
#' @examples
#' my_fun_rdname2(2:20)
my_fun_rdname2 <- function(x, na.rm = TRUE) {
  if (!is.numeric(x)) {stop("x should be numeric")}
  stats::median(x, na.rm = na.rm)
}
``

```

### Use same `@filename` in function roxygen

`@filename` is recognized only by {fusen} as a proper roxygen tag to merge multiple function in the same R/test files.  
Its content is removed from the resulting "R/" file to avoid any interference with Roxygenize.

```md
# Title 1 for function 1

``{r function-fun_filename1}
#' My fun_filename1
#'
#' @param x Vector of Numeric values
#' @inheritParams stats::median
#'
#' @filename same_filename
#' @return
#' Median of vector x
#' @export
#'
#' @examples
#' my_fun_filename1(2:20)
my_fun_filename1 <- function(x, na.rm = TRUE) {
  if (!is.numeric(x)) {stop("x should be numeric")}
  stats::median(x, na.rm = na.rm)
}
``

# Title  2 for function 2

``{r function-fun_filename2}
#' My fun_filename2
#'
#' @param x Vector of Numeric values
#' @inheritParams stats::median
#'
#' @filename same_filename
#' @return
#' Median of vector x
#' @export
#'
#' @examples
#' my_fun_filename2(2:20)
my_fun_filename2 <- function(x, na.rm = TRUE) {
  if (!is.numeric(x)) {stop("x should be numeric")}
  stats::median(x, na.rm = na.rm)
}
``

```

### Use chunk param `filename = "the_comon_filename"`

Add it in the `function` chunk only

```md
`{r function-fun_chunk2, filename = "fun_chunk1"}
#' The code of your function
`

```

**Comment by statnmap** [comment]
Use a `development` chunk at the beginning to list the different packages you need to load during development of your code, just like any other Rmd file.  
However, do not forget to declare your dependencies in the roxygen skeleton of your functions with `@importFrom`

**Comment by MargotBr** [comment]
## How to inflate all the `flat_*.Rmd` files?

In a `dev_history.R` file, before references to `{attachment}`, `devtools::check()` and `{renv}`:

```
# Create a function to inflate a given `flat_*.Rmd` file stored in `dev/`
inflate_a_given_flat <- function(name_flat_rmd) {

  flat_in_line <- readLines(file.path("dev", name_flat_rmd))

  start_inflate_chunk_in_code <- which(stringr::str_detect(flat_in_line, "fusen::inflate\\(rmd ="))

  inflate_code <- flat_in_line[start_inflate_chunk_in_code : (start_inflate_chunk_in_code + 3)] %>% stringr::str_c(collapse = "")

  eval(parse(text = inflate_code))

  return(message(glue::glue("{name_flat_rmd} inflate ok")))

}

# Launch the function for all `flat_*.Rmd` files stored in `dev/`
list.files("dev")[list.files("dev") %>% stringr::str_detect("^flat")] %>%
  purrr::walk(inflate_a_given_flat)
```
