### ISSUE TITLE
Not open a vignette in inflate

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/fusen#86]
Sometimes, I don't want to have my vignette open up : 
- because I will delete it #50 
- or I want to continue in my dev_history.Rmd.

I would suggest to add a param `fusen::inflate(open_vignette = )`

**Comment by statnmap** [comment]
I can't do anything about it for now, because it uses {usethis}, which does not allow for such functionality.  
Maybe we can find a workaround, but for now, I did not.

However, there is an issue about not creating a vignette at all there: https://github.com/ThinkR-open/fusen/issues/50
